server:
  port: 8080

spring:
  #  Spring Mvc相关配置
  mvc:
    # 静态资源路径
    static-path-pattern: /static/**
  web:
    resources:
      # 静态资源路径
      static-locations: classpath:/static,classpath:/public,file:SystemData
      # 轮播图路径
      carousel-path: classpath:/static/carousel

  servlet:
    multipart:
      # 单个文件最大上传大小
      max-file-size: 10MB
      # 单次请求最大文件上传大小
      max-request-size: 10MB

  #  # 数据库配置
#  datasource:
#    url: jdbc:mysql://campus-network.lanut.top:3306/WeChatOrderingCourseDesign?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: WeChatOrderingCourseDesign
#    password: e64xEMy4bCMp2hBa
#    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:mysql://8.222.189.149:3306/WeChatOrderingCourseDesign?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: WeChatOrdering
#    password: e64xEMy4bCMp2hBa
#    driver-class-name: com.mysql.cj.jdbc.Driver

  datasource:
    url: jdbc:mysql://localhost:3306/wechat_ordering_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  #Jwt配置
  security:
    jwt:
      # noinspection SpellCheckingInspection
      key: WeChatOrderingBackend&werfghnbvcxserthniuytfcxser
      expire: 604800

# 启用数据库日志
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 配置微信小程序的appid和secret
wechat:
  appid: wx7b12807502e80945
  secret: 0de65cf56c6e7d9e72f950b95f9be7ee
