server:
  port: 8080

spring:
  #  Spring Mvc相关配置
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://campus-network.lanut.top:28139/WeChatOrderingCourseDesign?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: WeChatOrderingCourseDesign
    password: e64xEMy4bCMp2hBa
    driver-class-name: com.mysql.cj.jdbc.Driver

#  datasource:
#    url: jdbc:mysql://localhost:3306/wechat_ordering_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
#    username: root
#    password: admin
#    driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis:
#  configuration:
#    #下划线转驼峰
#    map-underscore-to-camel-case: true