server:
  port: 8080

spring:
  #  Spring Mvc相关配置
  mvc:
    static-path-pattern: /static/**

  datasource:
    url: jdbc:mysql://campus-network.lanut.top:28139/WeChatOrderingCourseDesign
    username: WeChatOrderingCourseDesign
    password: e64xEMy4bCMp2hBa
    driver-class-name: com.mysql.cj.jdbc.Driver